name: Deploy Angular App 

on:
  push:
    branches:
      - main  # Or use 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Angular app
        run: ng build -- --configuration production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to GitHub Pages
        run: |
          cd dist/ride-now
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin git@github.com:hamidmeer4/RideNow.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push -f origin gh-pages
